package main

const indexHTML = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TubeControl</title><style>
:root{font-family:Segoe UI,Arial,sans-serif;color:#222;background:#f5f6f8}body{margin:0}.wrap{max-width:1400px;margin:auto;padding:22px}.card{background:white;border-radius:16px;padding:18px;box-shadow:0 2px 12px #0001;margin-bottom:16px}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}button{border:0;border-radius:10px;padding:11px 16px;background:#5d22d6;color:white;font-weight:600;cursor:pointer}button.alt{background:#e8e8ee;color:#222}input,select{padding:10px;border:1px solid #ccd;border-radius:9px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:9px;border-bottom:1px solid #eee;text-align:left}tr.green{background:#dcf7df}tr.yellow{background:#fff4c9}tr.red{background:#ffd9d9}.hidden{display:none}.modal{position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;z-index:5}.modal .box{background:white;padding:24px;border-radius:16px;max-width:620px;width:90%;max-height:85vh;overflow:auto}.modal img{max-width:100%}.status{margin-left:auto;color:#666}
</style></head><body><div class="wrap"><h1>TubeControl</h1>
<div id="activation" class="card hidden"><h2>Активация Windows</h2><p>Введите одноразовый ключ вида <b>TC-XXXX-XXXX</b>. Первый ключ появляется в логах TubeControl API после обновления сервера.</p><div class="row"><input id="actKey" placeholder="TC-XXXX-XXXX" style="min-width:220px"><input id="pcName" placeholder="Имя компьютера"><button onclick="activate()">Активировать</button></div><div id="actMsg"></div></div>
<div id="app" class="hidden"><div class="card row"><input type="file" id="file" accept=".xlsx,.xlsm"><button onclick="importFile()">Импорт Excel</button><button onclick="loadTubes()">Синхронизировать</button><button onclick="exportRows()">Выгрузить</button><button onclick="phoneQR()">Подключить телефон</button><button onclick="devices()" class="alt">Устройства</button><button onclick="newWinKey()" class="alt">Новый ключ Windows</button><span class="status" id="state"></span></div>
<div class="card row"><input id="search" placeholder="Поиск THU / магазин / заказ" oninput="render()" style="min-width:320px"><select id="filter" onchange="render()"><option value="all">Все</option><option value="returned">Возвращённые</option><option value="transit">В пути</option><option value="overdue">Просроченные</option></select></div>
<div class="card"><table><thead><tr><th>THU</th><th>Дата отгрузки</th><th>Магазин</th><th>Заказ</th><th>Статус</th><th>Возвращён</th></tr></thead><tbody id="tbody"></tbody></table></div></div></div><div id="modal" class="hidden"></div>
<script>
let tubes=[],visible=[];
async function j(url,opt){let r=await fetch(url,opt),x={};try{x=await r.json()}catch(e){}if(!r.ok)throw new Error(x.error||x.details||('HTTP '+r.status));return x}
async function init(){let s=await j('/local/status');if(s.activated){document.querySelector('#app').classList.remove('hidden');state.textContent=s.device_name||'Активировано';await loadTubes()}else document.querySelector('#activation').classList.remove('hidden')}
async function activate(){try{await j('/local/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:actKey.value,device_name:pcName.value})});location.reload()}catch(e){actMsg.textContent=e.message}}
async function loadTubes(){state.textContent='Синхронизация...';try{let x=await j('/local/tubes');tubes=x.items||[];render();state.textContent='Записей: '+tubes.length}catch(e){state.textContent=e.message}}
function st(t){if(t.returned_at)return 'returned';let d=new Date(t.shipped_at+'T00:00:00');return (Date.now()-d.getTime())>30*86400000?'overdue':'transit'}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function render(){let q=search.value.trim().toLowerCase(),f=filter.value;visible=tubes.filter(function(t){return (!q||[t.thu,t.store_code,t.order_number].join(' ').toLowerCase().includes(q))&&(f==='all'||st(t)===f)});tbody.innerHTML=visible.map(function(t){let s=st(t),txt=s==='returned'?'Возвращён':s==='overdue'?'Просрочен':'В пути',cls=s==='returned'?'green':s==='overdue'?'red':'yellow';return '<tr class="'+cls+'"><td>'+esc(t.thu)+'</td><td>'+esc(t.shipped_at)+'</td><td>'+esc(t.store_code)+'</td><td>'+esc(t.order_number)+'</td><td>'+txt+'</td><td>'+esc(t.returned_at||'')+'</td></tr>'}).join('')}
async function importFile(){let f=file.files[0];if(!f)return alert('Выберите Excel');let fd=new FormData();fd.append('file',f);state.textContent='Импорт...';try{let x=await j('/local/import',{method:'POST',body:fd});alert('Импортировано: '+x.processed);await loadTubes()}catch(e){alert(e.message);state.textContent=e.message}}
async function exportRows(){let ids=visible.filter(function(t){return !t.returned_at}).map(function(t){return t.thu});let r=await fetch('/local/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({thus:ids})});if(!r.ok)return alert('Ошибка выгрузки');let b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='TubeControl_non_returned.xlsx';a.click();URL.revokeObjectURL(u)}
function show(html){modal.className='modal';modal.innerHTML='<div class="box">'+html+'<div style="margin-top:16px"><button onclick="closeM()">Закрыть</button></div></div>'}function closeM(){modal.className='hidden';modal.innerHTML=''}
async function phoneQR(){try{let x=await j('/local/enrollment',{method:'POST'});show('<h2>Подключение Android</h2><p>QR одноразовый и действует 10 минут. На телефоне ничего вводить не нужно.</p><img src="'+x.qr+'"><p><b>'+esc(x.code)+'</b></p>')}catch(e){alert(e.message)}}
async function newWinKey(){try{let x=await j('/local/windows-key',{method:'POST'});show('<h2>Ключ для другого Windows</h2><p>Одноразовый ключ действует 48 часов.</p><h2>'+esc(x.code)+'</h2>')}catch(e){alert(e.message)}}
async function devices(){try{let x=await j('/local/devices'),rows=(x.items||[]).map(function(d){let act=d.revoked_at?'Отключено':'Активно',btn=d.id===x.current_device_id?'Этот ПК':(!d.revoked_at?'<button onclick="revoke(\''+d.id+'\')">Отключить</button>':'');return '<tr><td>'+esc(d.name)+'</td><td>'+esc(d.kind)+'</td><td>'+act+'</td><td>'+btn+'</td></tr>'}).join('');show('<h2>Устройства</h2><table><tr><th>Имя</th><th>Тип</th><th>Статус</th><th></th></tr>'+rows+'</table>')}catch(e){alert(e.message)}}
async function revoke(id){if(!confirm('Отключить устройство?'))return;try{await j('/local/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id})});closeM();devices()}catch(e){alert(e.message)}}
init();
</script></body></html>`
