package main

const indexHTML = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TubeControl</title><style>
:root{font-family:Segoe UI,Arial,sans-serif;color:#222;background:#f5f6f8;--bg:#f5f6f8;--card:#fff;--text:#222;--muted:#666;--line:#eee;--alt:#e8e8ee;--alttext:#222}html.dark{--bg:#17191d;--card:#23262c;--text:#eef0f3;--muted:#aeb4bf;--line:#383d46;--alt:#353a44;--alttext:#eef0f3}body{margin:0;background:var(--bg);color:var(--text)}.wrap{max-width:1400px;margin:auto;padding:22px}.card{background:var(--card);border-radius:16px;padding:18px;box-shadow:0 2px 12px #0002;margin-bottom:16px}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}button{border:0;border-radius:10px;padding:11px 16px;background:#5d22d6;color:white;font-weight:600;cursor:pointer}button.alt{background:var(--alt);color:var(--alttext)}input,select{padding:10px;border:1px solid #8886;border-radius:9px;background:var(--card);color:var(--text)}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:9px;border-bottom:1px solid var(--line);text-align:left}tr.green{background:#dcf7df;color:#18351d}tr.yellow{background:#fff4c9;color:#493c0a}tr.red{background:#ffd9d9;color:#4d1919}.hidden{display:none}.modal{position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;z-index:5}.modal .box{background:var(--card);color:var(--text);padding:24px;border-radius:16px;max-width:700px;width:90%;max-height:85vh;overflow:auto}.modal img{max-width:100%}.status{margin-left:auto;color:var(--muted)}.spacer{flex:1}.small{font-size:12px;color:var(--muted)}
</style></head><body><div class="wrap"><div class="row"><h1>TubeControl</h1><span class="spacer"></span><button class="alt" onclick="toggleTheme()" id="themeBtn">Тёмная тема</button></div>
<div id="activation" class="card hidden"><h2>Активация Windows</h2><p>Введите одноразовый ключ вида <b>TC-XXXX-XXXX</b>. Он нужен только один раз — постоянный секрет приложение получит от сервера автоматически.</p><div class="row"><input id="actKey" placeholder="TC-XXXX-XXXX" style="min-width:220px"><input id="pcName" placeholder="Имя компьютера"><button onclick="activate()">Активировать</button></div><div id="actMsg"></div></div>
<div id="app" class="hidden"><div class="card row"><input type="file" id="file" accept=".xlsx,.xlsm"><button onclick="importFile()">Импорт Excel</button><button onclick="loadTubes()">Синхронизировать</button><button onclick="exportRows()">Выгрузить</button><button onclick="phoneQR()">Подключить телефон</button><button onclick="devices()" class="alt">Устройства</button><button onclick="newWinKey()" class="alt">Новый ключ Windows</button><span class="status" id="state"></span></div>
<div class="card row"><input id="search" placeholder="Поиск THU / магазин / заказ" oninput="render()" style="min-width:300px"><select id="filter" onchange="render()"><option value="all">Все статусы</option><option value="returned">Возвращённые</option><option value="transit">В пути</option><option value="overdue">Просроченные</option></select><label>С <input type="date" id="fromDate" onchange="render()"></label><label>По <input type="date" id="toDate" onchange="render()"></label><label>Просрочка, дней <input type="number" min="1" max="3650" id="overdueDays" style="width:70px" onchange="savePrefs();render()"></label><button class="alt" onclick="clearFilters()">Сбросить фильтры</button></div>
<div class="card"><div class="small" id="shown"></div><table><thead><tr><th>THU</th><th>Дата отгрузки</th><th>Магазин</th><th>Заказ</th><th>Статус</th><th>Возвращён</th></tr></thead><tbody id="tbody"></tbody></table></div></div></div><div id="modal" class="hidden"></div>
<script>
let tubes=[],visible=[];
function loadPrefs(){let theme=localStorage.getItem('tc_theme')||'light';document.documentElement.classList.toggle('dark',theme==='dark');themeBtn.textContent=theme==='dark'?'Светлая тема':'Тёмная тема';overdueDays.value=localStorage.getItem('tc_overdue_days')||'30'}
function savePrefs(){let n=parseInt(overdueDays.value||'30',10);if(!Number.isFinite(n)||n<1)n=30;overdueDays.value=n;localStorage.setItem('tc_overdue_days',String(n))}
function toggleTheme(){let dark=!document.documentElement.classList.contains('dark');document.documentElement.classList.toggle('dark',dark);localStorage.setItem('tc_theme',dark?'dark':'light');themeBtn.textContent=dark?'Светлая тема':'Тёмная тема'}
async function j(url,opt){let r=await fetch(url,opt),x={};try{x=await r.json()}catch(e){}if(!r.ok)throw new Error(x.error||x.details||('HTTP '+r.status));return x}
async function init(){loadPrefs();let s=await j('/local/status');if(s.activated){document.querySelector('#app').classList.remove('hidden');state.textContent=s.device_name||'Активировано';await loadTubes()}else document.querySelector('#activation').classList.remove('hidden')}
async function activate(){try{await j('/local/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:actKey.value,device_name:pcName.value})});location.reload()}catch(e){actMsg.textContent=e.message}}
async function loadTubes(){state.textContent='Синхронизация...';try{let x=await j('/local/tubes');tubes=x.items||[];render();state.textContent='Записей: '+tubes.length}catch(e){state.textContent=e.message}}
function st(t){if(t.returned_at)return 'returned';let d=new Date(t.shipped_at+'T00:00:00'),days=parseInt(overdueDays.value||'30',10)||30;return (Date.now()-d.getTime())>days*86400000?'overdue':'transit'}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function render(){let q=search.value.trim().toLowerCase(),f=filter.value,fr=fromDate.value,to=toDate.value;visible=tubes.filter(function(t){let text=[t.thu,t.store_code,t.order_number].join(' ').toLowerCase();return (!q||text.includes(q))&&(f==='all'||st(t)===f)&&(!fr||t.shipped_at>=fr)&&(!to||t.shipped_at<=to)});tbody.innerHTML=visible.map(function(t){let s=st(t),txt=s==='returned'?'Возвращён':s==='overdue'?'Просрочен':'В пути',cls=s==='returned'?'green':s==='overdue'?'red':'yellow';return '<tr class="'+cls+'"><td>'+esc(t.thu)+'</td><td>'+esc(t.shipped_at)+'</td><td>'+esc(t.store_code)+'</td><td>'+esc(t.order_number)+'</td><td>'+txt+'</td><td>'+esc(t.returned_at||'')+'</td></tr>'}).join('');shown.textContent='Показано: '+visible.length+' из '+tubes.length}
function clearFilters(){search.value='';filter.value='all';fromDate.value='';toDate.value='';render()}
async function importFile(){let f=file.files[0];if(!f)return alert('Выберите Excel');let fd=new FormData();fd.append('file',f);state.textContent='Импорт...';try{let x=await j('/local/import',{method:'POST',body:fd});alert('Импортировано: '+x.processed);file.value='';await loadTubes()}catch(e){alert(e.message);state.textContent=e.message}}
async function exportRows(){let ids=visible.filter(function(t){return !t.returned_at}).map(function(t){return t.thu});if(ids.length===0)return alert('В текущем фильтре нет невозвращённых тубусов');let r=await fetch('/local/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({thus:ids})});if(!r.ok)return alert('Ошибка выгрузки');let b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='TubeControl_non_returned.xlsx';a.click();URL.revokeObjectURL(u)}
function show(html){modal.className='modal';modal.innerHTML='<div class="box">'+html+'<div style="margin-top:16px"><button onclick="closeM()">Закрыть</button></div></div>'}function closeM(){modal.className='hidden';modal.innerHTML=''}
async function phoneQR(){try{let x=await j('/local/enrollment',{method:'POST'});show('<h2>Подключение Android</h2><p>QR одноразовый и действует 10 минут. На телефоне ничего вводить не нужно.</p><img src="'+x.qr+'"><p class="small">Код: <b>'+esc(x.code)+'</b></p>')}catch(e){alert(e.message)}}
async function newWinKey(){try{let x=await j('/local/windows-key',{method:'POST'});show('<h2>Ключ для другого Windows</h2><p>Одноразовый ключ действует 48 часов.</p><h2>'+esc(x.code)+'</h2>')}catch(e){alert(e.message)}}
async function devices(){try{let x=await j('/local/devices'),rows=(x.items||[]).map(function(d){let act=d.revoked_at?'Отключено':'Активно',kind=d.kind==='android'?'Android':'Windows',seen=d.last_seen_at?new Date(d.last_seen_at).toLocaleString():'—',btn=d.id===x.current_device_id?'Этот ПК':(!d.revoked_at?'<button onclick="revoke(\''+d.id+'\')">Отключить</button>':'');return '<tr><td>'+esc(d.name)+'</td><td>'+kind+'</td><td>'+act+'</td><td>'+esc(seen)+'</td><td>'+btn+'</td></tr>'}).join('');show('<h2>Устройства</h2><table><tr><th>Имя</th><th>Тип</th><th>Статус</th><th>Последняя связь</th><th></th></tr>'+rows+'</table>')}catch(e){alert(e.message)}}
async function revoke(id){if(!confirm('Отключить устройство? После этого его ключ перестанет работать.'))return;try{await j('/local/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id})});closeM();devices()}catch(e){alert(e.message)}}
init();
</script></body></html>`
